CREATE TABLE USER (
id INT(3) UNSIGNED AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
level INT(3) NOT NULL,
xp INT(10) NOT NULL,
goal VARCHAR(250),
description VARCHAR(250),
reg_date TIMESTAMP NOT NULL,
PRIMARY KEY(id)
);

INSERT INTO USER(, column2, column3,...)

CREATE TABLE ACTIVITIES (
id INT(3) UNSIGNED AUTO_INCREMENT,
user_email VARCHAR(50) UNIQUE NOT NULL,
activity_json VARCHAR(255) UNIQUE NOT NULL, 
date_created TIMESTAMP NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (user_email) REFERENCES USER(email)
);

CREATE TABLE BADGES (
id INT(3) UNSIGNED AUTO_INCREMENT,
user_email VARCHAR(50) UNIQUE NOT NULL,
badges_json VARCHAR(255) UNIQUE NOT NULL, 
date_created TIMESTAMP NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (user_email) REFERENCES USER(email)
);

CREATE TABLE LEVEL_INFORMATION (
user_level INT(3) UNSIGNED,
title VARCHAR(20) NOT NULL,
description VARCHAR(250),
PRIMARY KEY(user_level)
);

CREATE TABLE BADGES_INFORMATION(
id INT(3) UNSIGNED AUTO_INCREMENT,
badge_requirement INT(10) UNSIGNED NOT NULL,
activity_type VARCHAR(10) NOT NULL,
title VARCHAR(20) NOT NULL,
description VARCHAR(250),
PRIMARY KEY(id)
);
