CREATE TABLE USER (
id INT(3) UNSIGNED AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
level INT(3) NOT NULL,
xp INT(10) NOT NULL,
goal VARCHAR(250),
description VARCHAR(250),
reg_date TIMESTAMP NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE ACTIVITIES (
id INT(3) UNSIGNED AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
description VARCHAR(250),
date_created TIMESTAMP NOT NULL,
PRIMARY KEY(id)
)